title: ainsbury.art
description: Resources for Computer Science & Creative iMedia
url: "https://ainsbury.art"   # you have a CNAME -> use your custom domain
baseurl: ""                   # leave empty for root site

markdown: kramdown
highlighter: rouge

# GitHub Pages–safe plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
